language: objective-c
osx_image: xcode7.2
sudo: false
script: 
 - set -o pipefail && xcodebuild build  -workspace OpenPics.xcworkspace -scheme "OpenPics" -destination "platform=iOS Simulator,name=iPhone 6" -list | xcpretty -c
